export const APP_CONSTANTS = {
  MIN_AGE: 18,
  MAX_AGE: 80,
  MIN_PROFILE_PHOTOS: 1,
  MAX_PROFILE_PHOTOS: 6,
  MAX_MESSAGE_LENGTH: 2000,
  CHAT_HISTORY_LIMIT: 50,
  MAX_BIO_LENGTH: 500,
  MAX_NAME_LENGTH: 100,
  DEFAULT_LOCATION_RADIUS_KM: 50,
} as const;
